### ISSUE TITLE
Set up json-server and query for heatmap data

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#1]
This will be used to simulate the backend so the frontend can be progressed.

### Definition of done
- `json-server` can be queried for data

### Subtasks
- [x] Install `json-server` as dev dependency
- [x] Create `db.json` in `client`
- [x] Add script to `package.json`
- [x] Add API call to server to `GET` heatmap data and render

### Acceptance criteria
N/A

### Useful resources
- https://www.npmjs.com/package/json-server
