### ISSUE TITLE
Add "my day" component

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#16]
Create a component which allows the user to record how they are feeling, and save it to the database.

### Definition of done
- Details can be recorded for the current day and saved to the database

### Subtasks
- [x] Create `/my-day` route and component
- [x] Add nav link to `/my-day`
- [x] Create `ContentWrapper` component by composition?
- [x] Create form
- [x] Add option to select rating (styled radio button?)
- [x] Style form (color coding options)
- [x] Implement service to update database
- [x] Add link from dashboard

### Acceptance criteria
N/A

### Useful resources
- https://dribbble.com/shots/21111984-Integrations-Page-Online-Survey-Tools
- https://tailwindcomponents.com/component/radio-buttons-1
- https://unicodeplus.com/
- http://www.amp-what.com/unicode/search
