### ISSUE TITLE
Add an emoji picker for weather and life events

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#24]
Allow the user to choose an emoji rather than a score for the current day.

### Definition of done
- Replace scores with emojis (#4)

### Subtasks
- [x] Replace `MyDay` scores with emojis
- [x] Show emojis on `Heatmap`
- [x] Modify `Heatmap` formatting to ensure responsive design

Note: future enhancements moved to #45.

### Acceptance criteria
N/A

### Useful resources
- https://dribbble.com/shots/14332639-Case-Management-Knowledge-Management-System
- https://unicodeplus.com/
- http://www.amp-what.com/unicode/search
