### ISSUE TITLE
Enhance mobile navigation experience

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#29]
Implement a collapsible navigation bar and better layout on mobile devices.

### Definition of done
- Details can be recorded for the current day and saved to the database

### Subtasks
- [x] Create `mobHidden` state for navigaiton visibility
- [x] Hide navigation on mobile only when `mobHidden` is `true`
- [x] Show navigation on screen size `md:` and above in all cases
- [x] Add `toggleMobHidden` function and Tailwind CSS classes to allow navigation to be hidden
- [x] Customise text on mobile to make it clear that navigation can be shown/hidden

### Acceptance criteria
N/A

### Useful resources
N/A
