### ISSUE TITLE
Implement prop types

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#35]
Prop types allow validation and type checking to catch bugs.

### Definition of done
- Prop types are implemented as detailed below

### Subtasks
- [ ] `npm install --save prop-types`
- [ ] Implement prop types for `TaskList`
- [ ] Implement prop types for `ContentWrapper`

### Acceptance criteria
N/A

### Useful resources
- https://www.npmjs.com/package/prop-types
