### ISSUE TITLE
Add tagging functionality to MyDay page

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#4]
After #16 

Allow the user to add tags for the current day.

### Definition of done
- User can tag events in the `MyDay` component by typing
- Tags can be autofilled if there is a match (e.g. using the tab key or clicking)
- Tags can be viewed in the `Heatmap`

### Subtasks
- [x] Add input element to `MyDay` form
- [x] Enforce minimum and maximum lengths on tags
- [x] Add tag on `space` or `tab`
- [x] Display tags with delete option (cross)
- [x] Enforce maximum number of tags
- [x] Use `flex` on the input and `row-wrap` on the container, with styling, to simulate adding tags
- [x] Ensure no duplicate tags are stored (show error if so)
- [x] Ensure API stores tags
- [x] Display at least one tag on the `Heatmap`
- [ ] #26
- [ ] #27

### Acceptance criteria
N/A

### Useful resources
- https://dribbble.com/shots/14332639-Case-Management-Knowledge-Management-System
- https://unicodeplus.com/
- http://www.amp-what.com/unicode/search
