### ISSUE TITLE
Install Node.js and create wellness API

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#41]
Install Node.js and set up wellness API.

### Definition of done
- User can `GET` wellness data from backend
- User can `POST` wellness data to backend

### Subtasks
- [x] Install Node.js
- [x] Build out skeleton (`index`, `app`) and folder structure (`routes`, `controllers`, `models`)
- [x] Install Mongoose
- [x] Write tests for `Day` model
- [x] Create `Day` model with existing fields
- [x] Write tests for `day` controller
- [x] Create `day` controller with `create` and `get` functions
- [x] ~Write tests for `day` route~ (as the routes are simple and mplicitly covered by testing `app.js`)
- [x] Create `day(s)` route with `GET` and `POST` for now
- [x] Write tests for `app` using `supertest`
- [x] Link to frontend

### Acceptance criteria
- N/A

### Useful resources
- https://codeutopia.net/blog/2016/06/10/mongoose-models-and-unit-tests-the-definitive-guide/
- https://www.tutorialspoint.com/expressjs/expressjs_best_practices.htm#:~:text=ExpressJS%20-%20Best%20Practices%201%20Always%20begin%20a,and%20isolate%20routes%20to%20their%20own%20file.%20
