### ISSUE TITLE
Add an emoji picker with auto-suggest for weather and life events

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#45]
Allow the user to add emojis for the current day.  This is a major enhancement to #24.

### Definition of done
- User can choose emojis and add them similar to the existing tagging functionality (#4)
- Auto-suggest emojis for matching tags (requires configuration and ability to remove)

### Subtasks
- [ ] Add an emoji picker for the weather (sun, rain, wind, thunderstorms, etc.)
- [ ] Add an emoji picker for life events
- [ ] Extend to each category (people, activities, life events)
- [ ] Map certain tags to emojis (see if there is already a mapping)
- [ ] Add configuration to auto-suggest emojis when tags match
- [ ] Ensure ability to remove/re-add emojis (turn grey initially and colour as each one is added)

### Acceptance criteria
N/A

### Useful resources
- https://dribbble.com/shots/14332639-Case-Management-Knowledge-Management-System
- https://unicodeplus.com/
- http://www.amp-what.com/unicode/search
