### ISSUE TITLE
Implement React Query (Tanstack)

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#5]
Implement React Query and update API calls to use it.

### Definition of done
- React Query calls services for `GET` and `POST`.

### Subtasks
- [x] Install package: `npm i @tanstack/react-query`
- [x] Install ESLint Plugin Query: `npm i -D @tanstack/eslint-plugin-query`
- [x] Implement `QueryClientProvider`
- [x] Implement for Heatmap (GET)
- [x] Implement for MyDay (POST)

### Acceptance criteria
- All queries in the app should use React Query.

### Useful resources
- https://tanstack.com/query/v4/docs/react/installation
- https://tanstack.com/query/v4/docs/react/overview
- https://blog.logrocket.com/deep-dive-mutations-tanstack-query
- https://www.smashingmagazine.com/2022/01/building-real-app-react-query/#:~:text=First%2C%20we%20have%20to%20wrap%20our%20app%20with,%2F%3E%20%3CToastContainer%20%2F%3E%20%3C%2FQueryClientProvider%3E%20%3C%2FRouter%3E%20%3C%2FReact.StrictMode%3E%2C%20document.getElementById%20%28%27root%27%29%29%3B
