### ISSUE TITLE
Refactor TaskList component

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#51]
Refactor the `TaskList` component, adding a `Tasks` component above.  and React Query. This will make handling the `isLoading` and `isError` states simpler.

### Definition of done
- The same functionality is achieved with smaller, individual components.

### Subtasks
- [x] Group `Tasks` components into a common folder
- [x] Rename `TaskList` to `Tasks`
- [x] Extract `TaskList` from `Tasks`
- [x] Clean up components

### Acceptance criteria
- N/A

### Useful resources
- N/A
