### ISSUE TITLE
Create side navigation bar

### ISSUE THREAD

**Issue by parradam** [parradam/wellwellwell#6]
This will hold the detailed links for easy navigation, starting with the dashboard.

### Definition of done
- Navigation bar can be used to navigate from one page to another

### Subtasks
- [x] Build left navigation bar
- [x] Style with Tailwind CSS
- [x] Add icons as appropriate
- [x] Install `react-router-dom`
- [x] Implement dashboard route (abstract into `routes` file)
- [x] Add `Link` component to `Nav` to navigate to dashboard

### Acceptance criteria
N/A

### Useful resources
- https://dribbble.com/shots/20530181-Sidebar-navigation-Untitled-UI
- https://unicodeplus.com/
- http://www.amp-what.com/unicode/search
